# Generated by Django 4.1 on 2022-09-01 14:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_unit', models.CharField(blank=True, default='千克', max_length=20, verbose_name='数量单位')),
                ('unit_in_stock', models.IntegerField(blank=True, default=0, verbose_name='入库数量')),
                ('price_in_stock', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='入库单价')),
                ('unit_on_order', models.IntegerField(blank=True, default=0, verbose_name='已售数量')),
                ('time_in_stock', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='商品')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
            },
        ),
    ]
