# Generated by Django 3.2.15 on 2022-08-31 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_price_on_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price_on_order',
        ),
    ]
