# Generated by Django 4.1 on 2022-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='客户')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
    ]
