# Generated by Django 4.1 on 2022-09-01 14:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='数量')),
                ('quantity_unit', models.CharField(blank=True, default='千克', max_length=20, verbose_name='数量单位')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='单价')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='总价')),
                ('time_on_order', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer', verbose_name='客户')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.stock', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
